#: import navigation_screen_manager navigation_screen_manager
#: import initial_access initial_access
#: import doctor_screens doctor_screens

MyScreenManager:

<MyScreenManager>:
    InitialAccessScreen:
        name: 'initial_access'
    SignUpScreen:
        name: 'sign_up'
    LoginScreen:
        name: 'login'
    HomeScreen:
        name: 'home'
    DoctorHomeScreen:
        name: 'doctor_home'
    DoctorMenuScreen:
        name: 'doctor_menu'
