

<BoxLayoutWithActionBar>:

 
    orientation: "vertical"
    ActionBar:
        ActionView:
            ActionPrevious:
                title: root.title
                on_release: app.manager.pop() ## só quando o usuário solta o botão

## Dava para fazer root.parent.parent.pop()
## root sempre se refere ao widget da classe principal do bloco

                app_icon: "images/lab_logo.png"
                app_icon_height: "20dp"
                app_icon_width: "20dp"



